export const LOADING_USERS = "LOADING_USERS";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_ERROR = "GET_SEARCH_ERROR";
export const RESET_SEARCH_DATA = "RESET_SEARCH_DATA";

export const LOADING_USER = "LOADING_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const LOADING_USER_REPOS = "LOADING_USER_REPOS";
export const GET_USER_REPOS_SUCCESS = "GET_USER_REPOS_SUCCESS";
export const GET_USER_REPOS_ERROR = "GET_USER_REPOS_ERROR";

export const LOADING_USER_FOLLOW = "LOADING_USER_FOLLOW";
export const GET_USER_FOLLOW_SUCCESS = "GET_USER_FOLLOW_SUCCESS";
export const GET_USER_FOLLOW_ERROR = "GET_USER_FOLLOW_ERROR";